services:
  express-app:
    build: .
    container_name: express-app
    ports:
      - "4242:4242"
    environment:
      - NODE_ENV=production
      - PORT=4242
      - DATABASE_URL=postgres://postgres:password@postgres:5432/mydatabase
      - REDIS_URL=redis://redis:6379
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - INFURA_API_KEY=${INFURA_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
